---
title: "Prerequisites"
---

## Minimum System Requirements

::: panel-tabset
## Windows

-   **OS:** Windows 10/11

-   **Memory:** \> 8 GB RAM

-   **ROM:** storage using Solid-state drive (SSD) is preferable. ([Here's how to check](https://www.lifewire.com/is-my-storage-ssd-or-hdd-5191369))

## macOS

-   **OS:** macOS 11 (Big Sur) or higher

-   **Memory:** \> 8 GB RAM
:::

::: callout-tip
In addition, users with some experience with R are beneficial. This workshop focuses on intermediate knowledge of R for managing and visualizing data. We recommend that participants familiarize themselves with the basics of R before attending this workshop. Here we also provide some online courses that would be helpful:

-   [R Programming Tutorial - Learn the Basics of Statistical Computing](https://youtu.be/_V8eKsto3Ug) from freecodecamp.org

-   [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r) from Datacamp

-   [A (very) short introduction to R](https://github.com/ClaudiaBrauer/A-very-short-introduction-to-R/blob/master/documents/A%20(very)%20short%20introduction%20to%20R.pdf): The 10-page document by Torfs & Brauer with background information and exercises, plus 2 pages with a list of useful functions. Working through this document takes a couple of hours (depending on your background knowledge).
:::

## Software Requirements

Before the workshop day, users are asked to install the following software in advance.

### 1. Install R

R is programming language for statistical computing and graphical visualization, and is an open-source software for computing in R language.

Users can download R installer from the Comprehensive R Archive Network (CRAN): [https://cran.rstudio.com](https://cran.rstudio.com/).

> The latest R version is `4.3.0 (2023-04-21) -- "Already Tomorrow"`.

### 2. Install Rtools (Windows users only)

Rtools is used to build and install R packages from source code. Some important tools, such as tidyverse, require Rtools to install on Windows.

Users can install Rtools from CRAN: <https://cran.rstudio.com/bin/windows/Rtools/rtools43/rtools.html>

> The current Rtools for Windows users is `Rtools 4.3`, which is compatible with version R 4.3.x.

### 3. Install Rstudio Desktop

Rstudio is an integrated development environment (IDE) for computing in R language. Users can install Rstudio Desktop from official posit website <https://posit.co/download/rstudio-desktop>.

> Current Rstudio Desktop version is `Released: 2023-03-16`.

### 4. Install necessary R packages

Participants are required to install the following R packages before the workshop day.

```{r}
install.packages(
  c(
    "ggplot2",
    "tidyverse",
    "ggmap",
    "pheatmap",
    "devtools",
    "cowplot",
    "reshape2",
    "dplyr",
    "wesanderson",
    "scales",
    "ggthemes",
    "ggrepel",
    "ggpubr",
    "gridExtra",
    "gganimate",
    "shiny",
    "rsconnect",
    "grid",
    "shinythemes",
    "colourpicker"
  ),
  dependencies = TRUE
)

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install(c("ggtree", "treeio"))
```
